apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-app.fullname" . }}-backend-service
  labels:
  {{- include "kafka-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  selector:
    app: backend
  {{- include "kafka-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backendService.ports | toYaml | nindent 2 }}