apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-app.fullname" . }}-frontend-service
  labels:
  {{- include "kafka-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: frontend
  {{- include "kafka-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.frontendService.ports | toYaml | nindent 2 }}